orbs:
  repo:
    executors:
      default:
        docker:
          - image: circleci/node:12

    commands:
      test:
        steps:
          - checkout
          - restore_cache:
              keys:
                - &cache_key npm_cache-{{ .Branch }}
                - npm_cache-

          - run:
              name: Install Dependencies
              command: npm ci

          - save_cache:
              key: *cache_key
              paths:
                - ~/.npm

          - run:
              name: Run Test
              command: npm test

      publish:
        steps:
          - run:
              name: Publish
              command: npx semantic-release

    jobs:
      default:
        executor: default
        steps:
          - test

      master:
        executor: default
        steps:
          - test
          - publish

version: 2.1

workflows:
  main:
    jobs:
      - repo/default:
          filters:
            branches:
              ignore:
                - master

      - repo/master:
          filters:
            branches:
              only:
                - master
